parameters:
#    chi_to_pik_store.example.class: ChiToPik\StoreBundle\Example

services:
#    chi_to_pik_store.example:
#        class: %chi_to_pik_store.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
